config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  
  end

  resources :users
  resources :friend_requests, only: [:create, :destroy, :update]
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :likes, only: :create
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: :sending_user_id
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: :receiving_user_id

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy, foreign_key: :commenter_id

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100", mini: "50x50#", micro: "30x30#"}

  # has_many :friends, -> { where(friend_requests: { accepted: true}) }, through: :friend_requests,
  #           foreign_key: :receiving_user_id, source: :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 3.megabytes

  validates :name, :surname, presence: true
  validates_attachment :avatar,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }



  def friends
   friends =  self.sent_friend_requests.where("accepted = ?", true).collect { |f| f.receiving_user_id }
   friends += self.received_friend_requests.where("accepted = ?", true).collect { |f| f.sending_user_id }
   User.where(id: friends)
  end

  def new_friend_req
    self.received_friend_requests.where(accepted:false).count
  end

  def liked? post
    self.liked_posts.include?(post)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name.split(' ').first   # assuming the user model has a name
      user.surname = auth.info.name.split(' ').last
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
      end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]


  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url if Rails.env.development?
      redirect_to 'https://odin-facebook11.herokuapp.com/'
    end
  end

  def failure
    redirect_to unauthenticated_root_path
  end


  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    if resource.persisted?
      UserMailer.welcome_email(resource).deliver_now
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :avatar, :email, :password, :password_confirmation])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   user_path(@user)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]

  def show
    @user = User.find(params[:id])
    @friends = @user.friends
  end

  def index
    @users = User.where.not(["id = ?", current_user.id]).paginate(page: params[:page], per_page: 20)
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_requests.html.erb
<div class="row">
  <div class="col-xs-6">
    <h5>Received friend requests from:</h5>
    <ul class="list-group">
      <% @user.received_friend_requests.each do |r| %>
        <% unless r.accepted %>
            <li class="list-group-item">
              <% u = User.find(r.sending_user_id) %>
                <%= u.name %> <%= u.surname %>
                <%= form_tag friend_request_path, method: :put, class: 'form-inline' do %>
                  <%= hidden_field_tag :update_id, r.sending_user_id %>
                <%= submit_tag "Accept", class: 'btn btn-primary btn-sm' %>
              <% end %>
            </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-6">
    <h5>Sent friend requests to:</h5>
      <ul class="list-group" >
        <% @user.sent_friend_requests.each do |r| %>
          <% unless r.accepted %>
            <% u = User.find(r.receiving_user_id) %>
              <li class='list-group-item'><%= u.name %> <%= u.surname %></li>
            <% end %>
        <% end %>
      </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">All Users</h1>
    <%= will_paginate %>
    <% @users.each do |user| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= user.name %> <%= user.surname %>
            <%= form_tag friend_requests_path, class: 'pull-right' do %>
              <%= hidden_field_tag :id_receiving, user.id %>
              <% unless current_user.friends.include?(user) %>
                <%= submit_tag 'Send friend request', class: 'btn btn-primary btn-sm' %>
              <% else %>
                <%= submit_tag 'Send friend request', class: 'btn btn-primary btn-sm', disabled: 'disabled' %>
              <% end %>
            <% end %>
        </div>
      </div>
    <% end %>
    <%= will_paginate %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="well">
      <h3 class="centered">My Profile</h3>
        <blockquote><label>Name:    </label> <%= @user.name %></blockquote>
        <blockquote><label>Surname: </label> <%= @user.surname %></blockquote>
        <blockquote><label>Email:   </label> <%= @user.email %></blockquote>
        <blockquote><%= image_tag @user.avatar.url(:medium), class: "img-rounded" %></blockquote>
        <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary' %>
      <hr />
      <h4><%= @user.name %>`s Posts</h4>
      <% @user.posts.each do |post| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= post.content %>
          </div>
        </div>
      <% end %>
      <hr />
      <h4>Friends:</h4>
      <ul class="list-group">
        <% @friends.each do |f|  %>
          <%= link_to user_path(f.id) do %>
            <li class="list-group-item">
              <%= f.name %> <%= f.surname %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <% if current_user?(@user) %>
        <%= render 'friend_requests' %>
      <% end %>

    </div>
  </div>
</div>