config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  
  end

  resources :users
  resources :friend_requests, only: [:create, :destroy, :update]
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :likes, only: :create
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, dependent: :destroy

  default_scope -> { order(created_at: :desc)}

  has_attached_file :picture, styles: { medium: "300x300", thumb: "100x100", mini: "50x50!"}

  validates_attachment :picture,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  validates :content, presence: true, length: { minimum: 3, maximum: 255}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.where(author: current_user.friends.to_a << current_user)
    @new_post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
      if @post.save
        flash[:success] = "You made a new Post!"
        redirect_to posts_path
      else
        flash[:danger] = @post.errors.full_messages.to_sentence
        redirect_to posts_path
      end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy

  end

  private
    def post_params
      params.require(:post).permit(:content, :picture)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-6" style="margin-bottom: 15px">
    <%= render 'shared/new_post' %>
  </div>
  <div class="col-md-6">
    <% @posts.each do |post| %>
        <div class="panel panel-primary">
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-10 col-sm-11">
                <%= link_to post_path(post), class: 'no_dec' do %>
                  <%= truncate(post.content, length: 80) %>
                  <%= image_tag(post.picture, class: 'img-responsive img-rounded') if post.picture.present? %>
                  <hr />
                  <small>Author: <%= post.author.name %></small>
                  <small><%= post.created_at.strftime("%k:%M, #{post.created_at.day.ordinalize} %B %Y" )%></small>
                  <span class="pull-right">Comments: <%= post.comments.count %></span>
                <% end %>
              </div>
              <div class="col-xs-2 col-sm-1">
                <%= render :partial => 'shared/likes_form', :locals => {post: post} %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p>
              <%= image_tag @post.author.avatar(:mini), class: 'img-rounded' %>
              <span style="font-size:16px"><%= @post.author.name %> <%= @post.author.surname %></span>
              <small><%= @post.created_at.strftime("#{@post.created_at.day.ordinalize} %B %Y") %></small>
              <span class="pull-right">Likes: <%= @post.likes.count %></span>
            </p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <%= render :partial => 'shared/likes_form', :locals => {post: @post} %>
          </div>
        </div>
      </div>

      <div class="panel-body">
        <p>
          <%= @post.content %>
        </p>
        <%= image_tag(@post.picture, class: 'img-responsive img-rounded') if @post.picture.present? %>
        <hr />
        <h4><small>Comments</small></h4>

        <div class="row">
          <div class="col-md-12">
            <%= form_tag comments_path, method: :post do %>
              <%= hidden_field_tag :post_id, params[:id] %>
              <%= hidden_field_tag "comment[commenter_id]", current_user.id %>
              <div class="form-group">
                <%= text_field_tag "comment[body]", nil, class: 'form-control', placeholer: 'Your comment' %>
              </div>
              <div class="form-group">
                <%= submit_tag 'Comment!', class: 'btn btn-primary' %>
              </div>
            <% end %>
            <% @post.comments.each do |comment| %>
              <div class="well">
                <p>
                  <%= image_tag @post.author.avatar(:micro), class: 'img-rounded' %>
                  <%= link_to comment.commenter.name, user_path(comment.commenter) %> -
                  <small><%= time_ago_in_words(comment.created_at) %> ago</small>
                </p>
                <%= comment.body %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>