config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: "users/omniauth_callbacks"}

  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  
  end

  resources :users
  resources :friend_requests, only: [:create, :destroy, :update]
  resources :posts
  resources :comments, only: [:create, :destroy]
  resources :likes, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, :polymorphic => true
  belongs_to :commenter, class_name: "User"

  validates :body, presence: true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: :sending_user_id
  belongs_to :user, class_name: "User", foreign_key: :receiving_user_id

  validates_uniqueness_of :sending_user_id, scope: :receiving_user_id
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :likes, dependent: :destroy

  default_scope -> { order(created_at: :desc)}

  has_attached_file :picture, styles: { medium: "300x300", thumb: "100x100", mini: "50x50!"}

  validates_attachment :picture,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  validates :content, presence: true, length: { minimum: 3, maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_friend_requests, class_name: 'FriendRequest', foreign_key: :sending_user_id
  has_many :received_friend_requests, class_name: 'FriendRequest', foreign_key: :receiving_user_id

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy, foreign_key: :commenter_id

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100", mini: "50x50#", micro: "30x30#"}

  # has_many :friends, -> { where(friend_requests: { accepted: true}) }, through: :friend_requests,
  #           foreign_key: :receiving_user_id, source: :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 3.megabytes

  validates :name, :surname, presence: true
  validates_attachment :avatar,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }



  def friends
   friends =  self.sent_friend_requests.where("accepted = ?", true).collect { |f| f.receiving_user_id }
   friends += self.received_friend_requests.where("accepted = ?", true).collect { |f| f.sending_user_id }
   User.where(id: friends)
  end

  def new_friend_req
    self.received_friend_requests.where(accepted:false).count
  end

  def liked? post
    self.liked_posts.include?(post)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name.split(' ').first   # assuming the user model has a name
      user.surname = auth.info.name.split(' ').last
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
      end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :set_cache_buster

  helper_method :current_user?

  def current_user?(user)
    current_user == user
  end

  # def set_cache_buster
  #   response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
  #   response.headers["Pragma"] = "no-cache"
  #   response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  # end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    commentable = find_commentable
    comment = commentable.comments.build(comment_params)
    if comment.save
      flash[:success] = 'Comment posted!'
      redirect_back fallback_location: authenticated_root_path
    else
      flash[:danger] = comment.errors.full_messages.to_sentence
      redirect_back fallback_location: authenticated_root_path
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:body, :commenter_id)
    end

    def find_commentable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
      nil
    end

end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :authenticate_user!

  def create
    unless current_user.friends.ids.include?(params[:id_receiving].to_i)
      f = current_user.sent_friend_requests.build(receiving_user_id: params[:id_receiving])
        if f.save
          flash[:success] = 'Friend request sent'
          redirect_to users_path
        else
          flash[:danger] = 'You have already sent a friend request to this user!'
          redirect_to users_path
        end
    else
      flash[:danger] = "You are already friends!"
      redirect_to users_path
    end
  end

  def destroy

  end

  def update
    current_user.received_friend_requests.find_by(sending_user_id: params[:update_id]).update(accepted: true)
    redirect_to user_path(current_user)
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    liked_post = current_user.likes.build(likes_params)
    if liked_post.save
      flash[:success] = "You liked #{Post.find(params[:post][:post_id]).author.name}`s post"
      redirect_back(fallback_location: authenticated_root_path)
    else
      flash[:danger] = 'You already liked this post!'
      redirect_back(fallback_location: authenticated_root_path)
    end
  end


  private
    def likes_params
      params.require(:post).permit(:post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.where(author: current_user.friends.to_a << current_user)
    @new_post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
      if @post.save
        flash[:success] = "You made a new Post!"
        redirect_to posts_path
      else
        flash[:danger] = @post.errors.full_messages.to_sentence
        redirect_to posts_path
      end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy

  end

  private
    def post_params
      params.require(:post).permit(:content, :picture)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]

  def show
    @user = User.find(params[:id])
    @friends = @user.friends
  end

  def index
    @users = User.where.not(["id = ?", current_user.id]).paginate(page: params[:page], per_page: 20)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
        <p>
          <h4 style="text-align:center">
            <small>Created by Peter Mester</small>
            <%= link_to '<i class="fa fa-github"></i>'.html_safe, "https://github.com/peter665" %>
          </h4>
        </p>
      </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navlinks" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "ODIN Facebook", unauthenticated_root_url, class: "navbar-brand" %>
      </div>
    <div class="collapse navbar-collapse" id="navlinks">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Members", users_path %></li>
          <li><%= link_to 'My Profile', user_path(current_user.id) %></li>
          <% if current_user.new_friend_req > 0 %>
            <li>
              <%= link_to user_path(current_user.id), class:'btn btn-info' do %>
                 <span class='badge'> <%= current_user.new_friend_req %></span>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to(destroy_user_session_path, :method => :delete) do %>
              Logout(<%= current_user.name %>)
            <% end %>
          </li>
          <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar.url(:mini), class: "img-circle navpic" %>
          <% end %>
        </ul>
        <% else %>
        <%= link_to user_facebook_omniauth_authorize_path do %>
          <i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i>
        <% end %>
          <div class="nav navbar-nav navbar-right">
            <%= form_tag(session_path(resource_name), class: 'navbar-form') do %>
              <div class="form-group">
                <%= email_field_tag 'user[email]', nil, class: 'form-control input-sm navb', placeholder: "Email" %>
              </div>
              <div class="form-group">
                <%= password_field_tag 'user[password]', nil, class: 'form-control input-sm navb', placeholder: 'Password' %>
              </div>
              <div class="form-group">
                <%= submit_tag 'Login', class: 'btn btn-primary btn-sm' %>
              </div>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |type, mes| %>
        <div id="messages" class="alert alert-<%= type %>">
          <%= mes %>
        </div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_likes_form.html.erb
<% unless current_user.liked?(post)%>
  <%= button_to(likes_path, method: :post, params: { post: {post_id: post.id } },
      class: "btn btn-primary btn-sm",
      form: {style: 'display:inline;', class:'pull-right'}) do %>
        <i class="fa fa-thumbs-o-up fa-lg"></i>
  <% end %>
<% else %>
  <i class="fa fa-thumbs-up fa-lg pull-right blue"></i>
<% end %>

app/views/shared/_new_post.html.erb
<%= form_for @new_post, url: posts_path do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control', placeholder: 'Your post...' %>
  </div>

  <div class="form-group">
    <%= f.file_field :picture %>
  </div>

  <div class="text-center">
    <%= f.submit "Post It!", class: 'btn btn-primary btn-lg btn-block' %>
  </div>


<% end %>